-- Ciphera Database Schema for Supabase
-- Run this SQL to set up the database tables

-- Extraction Logs - Main table for tracking extraction sessions
CREATE TABLE IF NOT EXISTS extraction_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_path TEXT NOT NULL,
    target_path TEXT NOT NULL,
    total_archives INTEGER NOT NULL DEFAULT 0,
    successful INTEGER NOT NULL DEFAULT 0,
    failed INTEGER NOT NULL DEFAULT 0,
    password_used TEXT,
    version TEXT DEFAULT '5.0',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Archive Logs - Individual archive processing records
CREATE TABLE IF NOT EXISTS archive_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    filename TEXT NOT NULL,
    password_used TEXT,
    status TEXT NOT NULL CHECK (status IN ('success', 'failed', 'skipped')),
    file_size BIGINT,
    archive_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Password Usage History
CREATE TABLE IF NOT EXISTS password_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    password_hash TEXT NOT NULL,
    success_count INTEGER NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_attempt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Settings/Configuration
CREATE TABLE IF NOT EXISTS ciphera_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE extraction_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE archive_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE ciphera_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access for anon key
CREATE POLICY "Allow public read extraction_logs" ON extraction_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert extraction_logs" ON extraction_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read archive_logs" ON archive_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert archive_logs" ON archive_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read password_usage" ON password_usage FOR SELECT USING (true);
CREATE POLICY "Allow public insert password_usage" ON password_usage FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read ciphera_settings" ON ciphera_settings FOR SELECT USING (true);
CREATE POLICY "Allow public insert ciphera_settings" ON ciphera_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update ciphera_settings" ON ciphera_settings FOR UPDATE USING (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_extraction_logs_timestamp ON extraction_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_archive_logs_timestamp ON archive_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_archive_logs_status ON archive_logs(status);

-- Insert default settings
INSERT INTO ciphera_settings (key, value) VALUES 
    ('version', '5.0'),
    ('cloud_sync', 'true'),
    ('auto_update', 'true')
ON CONFLICT (key) DO NOTHING;
